version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: .devops/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .devops/scripts/install_composer_dependencies.sh
      timeout: 300
      runas: root
    - location: .devops/scripts/start_server.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: .devops/scripts/stop_server.sh
      timeout: 30
      runas: root